Repository 33rd-SOPKATHON-TEAM5/Server, pull requests merged in 2023-11, with the labels that each got.

#2 [CHORE] 프로젝트 초기 세팅
  .gitignore
  build.gradle
  src/main/java/sopt/org/sopkathonServer/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/sopkathonServer/common/exception/ErrorType.java
  src/main/java/sopt/org/sopkathonServer/common/exception/SuccessType.java
  src/main/java/sopt/org/sopkathonServer/common/exception/dto/ApiResponse.java
  src/main/java/sopt/org/sopkathonServer/common/exception/model/CustomException.java
  src/main/java/sopt/org/sopkathonServer/config/JpaAuditingConfig.java
  src/main/java/sopt/org/sopkathonServer/controller/HealthCheck.java
  src/main/java/sopt/org/sopkathonServer/domain/BaseTimeEntity.java
  src/main/resources/application.properties
Labels: ✨CHORE, 🦄예준🦄, ☄️PULL REQUEST

#5 [FEAT] GiftCard 엔티티 설계
  .gitignore
  src/main/java/sopt/org/sopkathonServer/common/example.txt
  src/main/java/sopt/org/sopkathonServer/controller/example.txt
  src/main/java/sopt/org/sopkathonServer/domain/GiftCard.java
  src/main/java/sopt/org/sopkathonServer/domain/example.txt
  src/main/java/sopt/org/sopkathonServer/infrastructure/GiftCardRepository.java
  src/main/java/sopt/org/sopkathonServer/infrastructure/example.txt
Labels: 🌱FEAT, ✨DATABASE, 🦄예준🦄, ☄️PULL REQUEST

#6 [FEAT] user엔티티 구현
  src/main/java/sopt/org/sopkathonServer/domain/User.java
Labels: 🌱FEAT, ✨DATABASE, 🐰보람🐰

#9 [FIX] 엔티티 클래스명 변경
  src/main/java/sopt/org/sopkathonServer/domain/Cry.java
  src/main/java/sopt/org/sopkathonServer/infrastructure/CryRepository.java
Labels: ✨CHORE, 🦄예준🦄, ☄️PULL REQUEST

#11 [FEAT] 나의 눈물 기록 등록 API 구현
  build.gradle
  src/main/java/sopt/org/sopkathonServer/common/exception/SuccessType.java
  src/main/java/sopt/org/sopkathonServer/common/exception/dto/ApiResponse.java
  src/main/java/sopt/org/sopkathonServer/config/SecurityConfig.java
  src/main/java/sopt/org/sopkathonServer/config/WebConfig.java
  src/main/java/sopt/org/sopkathonServer/controller/CryController.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/request/RegisterCryRequest.java
  src/main/java/sopt/org/sopkathonServer/domain/Cry.java
  src/main/java/sopt/org/sopkathonServer/service/CryService.java
  src/main/java/sopt/org/sopkathonServer/service/example.txt
Labels: 🌱FEAT, 👑API, ✨DATABASE, 🦄예준🦄, ☄️PULL REQUEST

#13 [FEAT] GPT 연동 및 선물카드 조회 API 구현
  build.gradle
  src/main/java/sopt/org/sopkathonServer/common/exception/ErrorType.java
  src/main/java/sopt/org/sopkathonServer/common/exception/SuccessType.java
  src/main/java/sopt/org/sopkathonServer/common/exception/dto/ApiResponse.java
  src/main/java/sopt/org/sopkathonServer/controller/CardController.java
  src/main/java/sopt/org/sopkathonServer/controller/CryController.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/request/CardMessageAIRequest.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/request/GetGiftCardResponse.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/request/RegisterCryRequest.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/response/RegisterCryResponse.java
  src/main/java/sopt/org/sopkathonServer/domain/Cry.java
  src/main/java/sopt/org/sopkathonServer/service/CardService.java
  src/main/java/sopt/org/sopkathonServer/service/CryService.java
Labels: 🌱FEAT, 👑API, 🦄예준🦄, ☄️PULL REQUEST

#16 [FIX] API 요청값 추가 구현
  src/main/java/sopt/org/sopkathonServer/common/advice/ControllerExceptionAdvice.java
  src/main/java/sopt/org/sopkathonServer/common/exception/ErrorType.java
  src/main/java/sopt/org/sopkathonServer/controller/dto/response/GetCryListResponse.java
  src/main/java/sopt/org/sopkathonServer/service/CryService.java
Labels: 🐞FIX, 👑API, 🦄예준🦄, ☄️PULL REQUEST
